### ISSUE TITLE
Mushrooms spawning everywhere and causing issues with player builds.

### ISSUE THREAD

**Issue by lochlanmcelroy** [casperge/RealisticSeasons-issues#40]
Hey there! Is there potentially a way to toggle the mushrooms spawning everywhere? It's causing issues for some of the players on my network, as they are replacing flowers and just spawning all over.

**Comment by lochlanmcelroy** [comment]
Nevermind, I've found it, apologies.

**Comment by lochlanmcelroy** [comment]
Nevermind, that was 'mooshrooms'

**Comment by casperge** [comment]
Mushrooms aren't the issue here, flowers are replaced everywhere. Flower replacement is quite a difficult one to solve, I will explain the system and why it works this way. Every action this plugin does in a season must be undone to keep it realistic. Here are a few examples:
- Flower placement in spring -> flower removal in all other seasons
- Snow and ice placement in winter -> snow and ice removal in all other seasons
- Snow destroying grass and flowers in winter -> regrowing grass and flowers in all other seasons

The plugin can't know which one it did place and which one it didn't. This is why it removes all flowers for example and not just the ones placed by the plugin. If you want to stop something from being removed, you'll also have to disable the placement of the thing it removes. In your case that would be flowers in spring. Setting flower-chance-in-spring to 1300 or higher will stop the placement of flowers, but also stop them from being removed. One issue that remains though is the fact that snow will still destroy the flowers in winter, meaning that players will have to replant everything after winter. If this is an issue, you should set snow-placement-enabled in the config.yml to false. This will stop snow blocks from being placed, but also stop flowers from being destroyed. Adding an option that disables only grass and flowers being destroyed by snow has been tried in the past, but it looked really weird and ugly in the world.

Hope this answers your question, let me know if you need any more help :)
